[package]
name = "eden-api"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
eden-api-types = { path = "../eden-api-types", features = ["server"] }
eden-background-worker = { path = "../eden-background-worker"}
eden-config = { path = "../eden-config" }
eden-jobs = { path = "../eden-jobs" }
eden-metrics = { path = "../eden-metrics" }
eden-model = { path = "../eden-model" }
eden-postgres = { path = "../eden-postgres" }
eden-services = { path = "../eden-services" }
eden-signals = { path = "../eden-signals" }
eden-test-util = { path = "../eden-test-util" }

axum-extra = { version = "0.12.5", features = ["typed-header"] }
axum-server = { version = "0.8.0", features = ["tls-rustls-no-provider", "tokio-rustls"] }
bon = { workspace = true }
erased-report = { path = "../erased-report" }
error-stack = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tower = "0.5.3"
tower-http = { version = "0.6.8", features = ["timeout"] }
tower-layer = "0.3.3"
tower-service = "0.3.3"
twilight-model = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
validator = { workspace = true }

[dependencies.axum]
version = "0.8.8"
default-features = false
features = [
    "http1",
    "json",
    "macros",
    "matched-path",
    "query",
    "tokio",
    "tower-log",
    "tracing"
]

[dev-dependencies]
axum-test = { version = "20.0.0" }
insta = { workspace = true }

[lints]
workspace = true
