[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.dependencies]
chrono = "0.4.45"
error-stack = "0.8.0"
hex = "0.4.3"
ipnet = "2.12.0"
rand = "0.10.2"
sha2 = "0.11.0"
thiserror = "2.0.19"
tokio = { version = "1.53.1", features = ["full"] }
uuid = "1.24.0"

[workspace.dependencies.diesel]
version = "2.3.11"
features = ["postgres", "chrono", "ipnet-address", "uuid"]

[workspace.lints]

[workspace.lints.clippy]
allow_attributes = "forbid"

[workspace.lints.rust]
unsafe_code = "deny"
