[package]
name = "xtask"
description = "A collection of custom build and utility tasks for the Eden backend repository."
version = "0.1.0"
edition = "2024"

[dependencies]
eden-env-vars = { path = "../crates/eden-env-vars" }
eden-test-harness = { path = "../crates/eden-test-harness" }
erased-report = { path = "../crates/erased-report" }

diesel = { workspace = true }
diesel_migrations = { workspace = true }
error-stack = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }

crc-fast = "1.10.0"
env_logger = "0.11.9"
log = "0.4.29"
xflags = "0.3.2"
xshell = "0.2.7"

[lints]
workspace = true
