xflags::xflags! {
    src "./src/flags.rs"

    /// Utility and build tasks for the Eden backend repository.
    cmd xtask {
        /// Runs unit tests for all crates excluding macros crates with cargo-nextest.
        ///
        /// If cargo-nextest cannot be found, it falls back to cargo test.
        cmd test {
        }
    }
}

// generated start
// The following code is generated by `xflags` macro.
// Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
#[derive(Debug)]
pub struct Xtask {
    pub subcommand: XtaskCmd,
}

#[derive(Debug)]
pub enum XtaskCmd {
    Test(Test),
}

#[derive(Debug)]
pub struct Test;

impl Xtask {
    #[allow(dead_code)]
    pub fn from_env_or_exit() -> Self {
        Self::from_env_or_exit_()
    }

    #[allow(dead_code)]
    pub fn from_env() -> xflags::Result<Self> {
        Self::from_env_()
    }

    #[allow(dead_code)]
    pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
        Self::from_vec_(args)
    }
}
// generated end
