#![expect(
    clippy::allow_attributes,
    reason = "xflags suppresses lints with #[allow(...)] automatically"
)]

xflags::xflags! {
    src "./src/flags.rs"

    /// Utility and build tasks for the Eden backend repository.
    cmd xtask {
        /// Runs unit tests across workspace crates with insta snapshot integration.
        ///
        /// Automatically falls back to `cargo test` if `cargo-nextest` is requested
        /// but not installed on the system.
        ///
        /// This command requires `DATABASE_URL` to be set in order to run this command,
        /// and PostgreSQL client utilities (specifically `pg_dump`) to be installed and
        /// accessible in `PATH`.
        cmd test {
            /// Uses `cargo-nextest` as the test runner instead of standard `cargo test`.
            ///
            /// Can also be enabled by setting the `EDEN_XTASK_USE_NEXTEST=1` environment variable.
            optional --nextest

            /// Specific crate name to test.
            ///
            /// If omitted, tests are executed across all workspace crates.
            optional krate: String
        }
    }
}

// generated start
// The following code is generated by `xflags` macro.
// Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
#[derive(Debug)]
pub struct Xtask {
    pub subcommand: XtaskCmd,
}

#[derive(Debug)]
pub enum XtaskCmd {
    Test(Test),
}

#[derive(Debug)]
pub struct Test {
    pub krate: Option<String>,

    pub nextest: bool,
}

impl Xtask {
    #[allow(dead_code)]
    pub fn from_env_or_exit() -> Self {
        Self::from_env_or_exit_()
    }

    #[allow(dead_code)]
    pub fn from_env() -> xflags::Result<Self> {
        Self::from_env_()
    }

    #[allow(dead_code)]
    pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
        Self::from_vec_(args)
    }
}
// generated end
