[package]
name = "eden-model"
version = "0.1.0"
edition = "2024"

[dependencies]
eden-database = { path = "../eden-database" }

chrono = { workspace = true }
diesel = { workspace = true }
error-stack = { workspace = true }
hex = { workspace = true }
ipnet = { workspace = true }
rand = { workspace = true }
rand_chacha = { version = "0.10.0" }
secrecy = "0.10.3"
sha2 = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }

[lints]
workspace = true
